version: '3'

volumes:
  blaze-data:

services:
  blaze-fhir:
    image: "samply/blaze:0.11.0"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      BASE_URL: "http://blaze-fhir:8080"
    ports:
      - "9090:8080"
    volumes:
      - "blaze-data:/app/data"

  kindling_test:
    container_name: kindling_test
    build: .
    volumes:
      - ./:/opt/coverage
    environment:
      - FHIR_API_URL=http://blaze-fhir:8080
    depends_on:
      - blaze-fhir

