[tool.poetry]
name = "fhir-kindling"
version = "0.9.6"
description = "Python library for working with FHIR servers and resources."
authors = ["Michael Graf <michael.graf3110@gmail.com>"]
readme = "README.md"
packages = [{ include = "fhir_kindling" }]

[tool.poetry.dependencies]
python = "^3.11"
"fhir.resources" = "*"
pendulum = "*"
tqdm = "*"
orjson = "*"
xmltodict = "*"
pydantic = "*"
networkx = "*"
httpx = "*"
authlib = "*"
pandas = { version = "*", optional = true }
plotly = { version = "*", optional = true }
sqlmodel = { version = "*", optional = true }
fastapi = { version = "*", optional = true }
uvicorn = { version = "*", optional = true }
cachetools = { version = "*", optional = true }
types-cachetools = { version = "*", optional = true }


[tool.poetry.extras]
ds = ["pandas", "plotly"]
app = ["fastapi", "uvicorn", "sqlmodel", "cachetools", "types-cachetools"]


[tool.poetry.group.dev.dependencies]
pytest = "*"
coverage = "*"
tox = "*"
mkdocs = "*"
mkdocs-material = "*"
twine = "*"
bump2version = "*"
notebook = "*"
jupyter = "*"
mkdocstrings = { extras = ["python-legacy"], version = "*" }
flake8 = "*"
ipython = ">=7.31.1"
pytest-asyncio = "*"
rise = "*"
python-dotenv = "*"
black = "^22.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
