# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  test:

    runs-on: ubuntu-latest
    container: python:3.9
    environment: CI
    services:
      hapi:
        image: "hapiproject/hapi:latest"
        env:
          hapi.fhir.default_encoding: json
          hapi.fhir.: json
          hapi.fhir.server_address: "http://hapi:8080/fhir"
        volumes:
          - hapi:/data/hapi

      blaze:
        image: "samply/blaze:latest"
        env:
          JAVA_TOOL_OPTIONS: "-Xmx2g"
          BASE_URL: "http://blaze:8080"
        volumes:
          - blaze:/app/data
    env:
      FHIR_API_URL: http://blaze:8080/fhir
      TRANSFER_API_URL: http://hapi:8080/fhir


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install deps
        run: poetry install --with dev --all-extras
      - run: pipenv install --dev
        name: Install dependencies
      - name: Prefill servers with data
        run: |
          poetry run pip install .
          poetry run pip install requests
          poetry run python ./testing/prefill.py

      - name: Lint with flake8
        run: |
          poetry run ruff -v .
      - name: Tests and coverage report
        run: |
          poetry run coverage run -m pytest fhir_kindling
          poetry run coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          name: codecov-umbrella
          verbose: true

      - name: Build and deploy documentation
        run: poetry run mkdocs gh-deploy --force
